name: Build macOS arm64
on:
  push:
    tags:
      - '*'
jobs:
  macOS:
    runs-on: macos-12
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ./make.rb macos-arm64
      - name: Upload binaries to release arm64
        uses: svenstaro/upload-release-action@v2
        with:
          file: tmp/bismite-mruby-macos-arm64.tgz
          asset_name: bismite-mruby-macos-arm64-${{github.ref_name}}.tgz
          overwrite: true
