name: Build Linux
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libgl-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev clang
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ./make.rb linux
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: tmp/bismite-mruby-linux.tgz
          asset_name: bismite-mruby-linux-${{github.ref_name}}.tgz
          overwrite: true
