name: Build macOS
on:
  push:
    tags:
      - "*"
jobs:
  macOS:
    runs-on: macos-14
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ./make.rb macos clean
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file: tmp/bismite-mruby-macos.tgz
          asset_name: bismite-mruby-macos-${{github.ref_name}}.tgz
          overwrite: true
