name: Build MinGW
on:
  push:
    tags:
      - '*'
jobs:
  mingw-w64:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: sudo apt-get install mingw-w64
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ./make.rb mingw
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tmp/bismite-mruby-mingw.tgz
          asset_name: bismite-mruby-mingw-${{github.ref}}.tgz
          tag: ${{ github.ref }}
          overwrite: true
