name: Build Linux
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libgl-dev clang
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ./make.rb linux
      - uses: actions/upload-artifact@v4
        with:
          name: bismite-mruby-linux-${{github.sha}}.tgz
          path: tmp/bismite-mruby-linux.tgz
      - name: Publish
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file: bismite-mruby-linux.tgz
          asset_name: bismite-mruby-linux-${{github.ref_name}}.tgz
          overwrite: true
