name: Build MinGW
on:
  push:
    tags:
      - "*"
jobs:
  mingw-w64:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: sudo apt-get install mingw-w64
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ./make.rb mingw
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file: tmp/bismite-mruby-mingw.tgz
          asset_name: bismite-mruby-mingw-${{github.ref_name}}.tgz
          overwrite: true
