name: Build Linux
on: [push, workflow_call]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libgl-dev clang
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ./make.rb linux
      - uses: actions/upload-artifact@v4
        with:
          name: bismite-mruby-linux-${{github.sha}}.tgz
          path: tmp/bismite-mruby-linux.tgz
