name: Build Linux
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libgl-dev clang
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ./make.rb linux
      - name: Upload binaries to release
        if: github.tag != ''
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file: tmp/bismite-mruby-linux.tgz
          asset_name: bismite-mruby-linux-${{github.ref_name}}.tgz
          overwrite: true
