name: Build Emscripten
on:
  push:
    tags:
      - '*'
env:
  EM_VERSION: 3.1.31
  EM_CACHE_FOLDER: 'emsdk-cache'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v3
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - run: ./make.rb emscripten clean
      - run: ./make.rb emscripten-nosimd clean
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: tmp/bismite-mruby-emscripten.tgz
          asset_name: bismite-mruby-emscripten-${{github.ref_name}}.tgz
          overwrite: true
      - name: Upload binaries to release (nosimd)
        uses: svenstaro/upload-release-action@v2
        with:
          file: tmp/bismite-mruby-emscripten-nosimd.tgz
          asset_name: bismite-mruby-emscripten-nosimd-${{github.ref_name}}.tgz
          overwrite: true
