name: Build macOS
on:
  push:
    tags:
      - '*'
jobs:
  macOS:
    runs-on: macos-12
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ./make.rb macos
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tmp/bismite-mruby-macos.tgz
          asset_name: bismite-mruby-macos-${{github.ref}}.tgz
          tag: ${{ github.ref }}
          overwrite: true
