name: Build
on:
  push:
    tags:
      - '*'
jobs:
  macOS-Build:
    runs-on: macos-10.15
    env:
      SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ./make.rb macos
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: macos.tgz
          asset_name: macos.tgz
          tag: ${{ github.ref }}
          overwrite: true
  linux-Build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: sudo apt-get install libgl-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev clang
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ./make.rb linux
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: linux.tgz
          asset_name: linux.tgz
          tag: ${{ github.ref }}
          overwrite: true
