name: Build Release
on: [push]
jobs:
  macOS-Build:
    runs-on: macos-10.15
    env:
      SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ./makr.rb macos
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: macos.tgz
          asset_name: macos.tgz
          tag: ${{ github.ref }}
          overwrite: true
