name: Release Linux
on:
  push:
    tags:
      - "*"
jobs:
  build:
    uses: ./.github/workflows/build-linux.yml
  release:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: bismite-mruby-linux-${{github.sha}}.tgz
          path: ./bismite-mruby-linux.tgz
      - run: ls -l
      - run: file *
      - uses: svenstaro/upload-release-action@2.9.0
        with:
          file: bismite-mruby-linux.tgz
          asset_name: bismite-mruby-linux-${{github.ref_name}}.tgz
          overwrite: true
